/* Dados do check-list (edite à vontade aqui) */
window.CHECKLIST_ITEMS = [
  { id: "portas",     local: "Verificação de portas • Acessos restritos",      desc: "Locais: CPD, sala dos elevadores, terraço, acessos restritos. <br> Os acessos estão devidamente fechadas?",                                                              periodicidade: "diaria",    tipo: "portas" },
  { id: "bomba_aud",  local: "Bomba de drenagem • Auditório",                  desc: "Relatar o funcionamento; <br> Verificar as Condições: <br> - Modo de trabalho e qual em operação",                                                                       periodicidade: "quinzenal", tipo: "bomba" },
  { id: "elev_pcd",   local: "Elevador PCD • Térreo",                          desc: "Verificar o funcionamento do elevador. <br> Há algum problema?",                                                                                                         periodicidade: "semanal",   tipo: "ok_nok" },
  { id: "bomba_esg",  local: "Bomba de drenagem do esgoto • logmans",          desc: "Relatar o funcionamento; <br> Verificar as Condições: <br> - Modo de trabalho e qual em operação",                                                                       periodicidade: "mensal",    tipo: "bomba" },
  { id: "subest",     local: "Sala da Sub-estação de energia • Subsolo",       desc: "As estações de energia estão devidamente fechadas? <br> O ambiente está em boas condições?",                                                                             periodicidade: "bimestral", tipo: "condicao" },
  { id: "cisterna",   local: "Cisterna • Subsolo",                             desc: "Verificar a condição do ambiente e o nível de água.",                                                                                                                    periodicidade: "quinzenal", tipo: "nivel" },
  { id: "banheiros",  local: "Banheiros",                                      desc: "Averiguar se há vazamentos, equipamentos danificados ou problemas em: vasos sanitários, trincos em portas ou estrutura. <br> O ambiente está em boas condições?",        periodicidade: "quinzenal", tipo: "ok_nok" },
  { id: "calhas",     local: "Inspeção das calhas",                            desc: "Verificar as calhas e a necessidade de limpeza presente no terraço, 1º andar e nas varandas das salas do 3º andar",                                                      periodicidade: "quinzenal", tipo: "limpeza" },
  { id: "hidrometro", local: "Hidrômetro",                                     desc: "Verificar se está aberto ou fechado e registrar a numeração.",                                                                                                           periodicidade: "semanal",   tipo: "hidrometro" },
  { id: "cx_gordura", local: "Caixa de gordura • gastronomia",                 desc: "Verificar a condição da caixa. <br> É necessário a limpeza?",                                                                                                            periodicidade: "semanal",   tipo: "limpeza" },
  { id: "cx_agua",    local: "Caixa d'água • Terraço",                         desc: "Verificar a condição e o nível de água.",                                                                                                                                periodicidade: "semanal",   tipo: "nivel" },
  { id: "cpd",        local: "Inspeção do <strong>CPD</strong> • 11 andar",    desc: "Verificar o ar. <br> As câmeras estão funcionando?<br> É necessário alguma intervenção?",                                                                                periodicidade: "semanal",   tipo: "cpd" },
  { id: "poco_elev",  local: "Poço do elevador • Subsolo",                     desc: "Verificar a condição durante as visitas da OTIS",                                                                                                                        periodicidade: "mensal",    tipo: "condicao" },
  { id: "elev_cist",  local: "Elevatória da cisterna • Subsolo",               desc: "Relatar o funcionamento; <br> Verificar as Condições: <br> - Modo de trabalho e qual em operação",                                                                       periodicidade: "bimestral", tipo: "bomba" },  
];
